/* Automatically generated by tree-sitter v0.25.1 (f5afe475deb7c0bae6407fb776c76824f717bb61) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 58
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_CLASS_DASHPOOL = 1,
  anon_sym_FUNCTION_DASHPOOL = 2,
  anon_sym_NO = 3,
  anon_sym_STANDARD = 4,
  anon_sym_PAGE = 5,
  anon_sym_HEADING = 6,
  anon_sym_LINE_DASHSIZE = 7,
  anon_sym_LINE_DASHCOUNT = 8,
  anon_sym_LPAREN = 9,
  anon_sym_RPAREN = 10,
  sym_interface_pool = 11,
  anon_sym_PROGRAM = 12,
  anon_sym_REPORT = 13,
  anon_sym_DEFINING = 14,
  anon_sym_DATABASE = 15,
  anon_sym_TYPE_DASHPOOL = 16,
  anon_sym_REDUCED = 17,
  anon_sym_FUNCTIONALITY = 18,
  anon_sym_MESSAGE_DASHID = 19,
  sym_identifier = 20,
  sym_number = 21,
  sym_terminate = 22,
  sym_source_file = 23,
  sym_introductory_statement = 24,
  sym_class_pool = 25,
  sym_function_pool = 26,
  sym_list_options = 27,
  sym_program = 28,
  sym_report = 29,
  sym_type_pool = 30,
  sym__reduced_functionality = 31,
  sym__message_id = 32,
  aux_sym_function_pool_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_CLASS_DASHPOOL] = "CLASS-POOL",
  [anon_sym_FUNCTION_DASHPOOL] = "FUNCTION-POOL",
  [anon_sym_NO] = "NO",
  [anon_sym_STANDARD] = "STANDARD",
  [anon_sym_PAGE] = "PAGE",
  [anon_sym_HEADING] = "HEADING",
  [anon_sym_LINE_DASHSIZE] = "LINE-SIZE",
  [anon_sym_LINE_DASHCOUNT] = "LINE-COUNT",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_interface_pool] = "interface_pool",
  [anon_sym_PROGRAM] = "PROGRAM",
  [anon_sym_REPORT] = "REPORT",
  [anon_sym_DEFINING] = "DEFINING",
  [anon_sym_DATABASE] = "DATABASE",
  [anon_sym_TYPE_DASHPOOL] = "TYPE-POOL",
  [anon_sym_REDUCED] = "REDUCED",
  [anon_sym_FUNCTIONALITY] = "FUNCTIONALITY",
  [anon_sym_MESSAGE_DASHID] = "MESSAGE-ID",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_terminate] = "terminate",
  [sym_source_file] = "source_file",
  [sym_introductory_statement] = "introductory_statement",
  [sym_class_pool] = "class_pool",
  [sym_function_pool] = "function_pool",
  [sym_list_options] = "list_options",
  [sym_program] = "program",
  [sym_report] = "report",
  [sym_type_pool] = "type_pool",
  [sym__reduced_functionality] = "_reduced_functionality",
  [sym__message_id] = "_message_id",
  [aux_sym_function_pool_repeat1] = "function_pool_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_CLASS_DASHPOOL] = anon_sym_CLASS_DASHPOOL,
  [anon_sym_FUNCTION_DASHPOOL] = anon_sym_FUNCTION_DASHPOOL,
  [anon_sym_NO] = anon_sym_NO,
  [anon_sym_STANDARD] = anon_sym_STANDARD,
  [anon_sym_PAGE] = anon_sym_PAGE,
  [anon_sym_HEADING] = anon_sym_HEADING,
  [anon_sym_LINE_DASHSIZE] = anon_sym_LINE_DASHSIZE,
  [anon_sym_LINE_DASHCOUNT] = anon_sym_LINE_DASHCOUNT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_interface_pool] = sym_interface_pool,
  [anon_sym_PROGRAM] = anon_sym_PROGRAM,
  [anon_sym_REPORT] = anon_sym_REPORT,
  [anon_sym_DEFINING] = anon_sym_DEFINING,
  [anon_sym_DATABASE] = anon_sym_DATABASE,
  [anon_sym_TYPE_DASHPOOL] = anon_sym_TYPE_DASHPOOL,
  [anon_sym_REDUCED] = anon_sym_REDUCED,
  [anon_sym_FUNCTIONALITY] = anon_sym_FUNCTIONALITY,
  [anon_sym_MESSAGE_DASHID] = anon_sym_MESSAGE_DASHID,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_terminate] = sym_terminate,
  [sym_source_file] = sym_source_file,
  [sym_introductory_statement] = sym_introductory_statement,
  [sym_class_pool] = sym_class_pool,
  [sym_function_pool] = sym_function_pool,
  [sym_list_options] = sym_list_options,
  [sym_program] = sym_program,
  [sym_report] = sym_report,
  [sym_type_pool] = sym_type_pool,
  [sym__reduced_functionality] = sym__reduced_functionality,
  [sym__message_id] = sym__message_id,
  [aux_sym_function_pool_repeat1] = aux_sym_function_pool_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_CLASS_DASHPOOL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FUNCTION_DASHPOOL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NO] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STANDARD] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PAGE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_HEADING] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LINE_DASHSIZE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LINE_DASHCOUNT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_interface_pool] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PROGRAM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_REPORT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DEFINING] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DATABASE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TYPE_DASHPOOL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_REDUCED] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FUNCTIONALITY] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MESSAGE_DASHID] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_terminate] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_introductory_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_class_pool] = {
    .visible = true,
    .named = true,
  },
  [sym_function_pool] = {
    .visible = true,
    .named = true,
  },
  [sym_list_options] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_report] = {
    .visible = true,
    .named = true,
  },
  [sym_type_pool] = {
    .visible = true,
    .named = true,
  },
  [sym__reduced_functionality] = {
    .visible = false,
    .named = true,
  },
  [sym__message_id] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_function_pool_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(113);
      ADVANCE_MAP(
        '(', 122,
        ')', 123,
        '.', 135,
        'C', 56,
        'D', 14,
        'F', 106,
        'H', 36,
        'I', 65,
        'L', 49,
        'M', 29,
        'N', 72,
        'P', 7,
        'R', 30,
        'S', 103,
        'T', 109,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(134);
      END_STATE();
    case 1:
      if (lookahead == '-') ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(85);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(52);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(87);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(88);
      if (lookahead == 'A') ADVANCE(61);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(89);
      END_STATE();
    case 7:
      if (lookahead == 'A') ADVANCE(46);
      if (lookahead == 'R') ADVANCE(74);
      END_STATE();
    case 8:
      if (lookahead == 'A') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'A') ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == 'A') ADVANCE(62);
      END_STATE();
    case 11:
      if (lookahead == 'A') ADVANCE(66);
      END_STATE();
    case 12:
      if (lookahead == 'A') ADVANCE(97);
      END_STATE();
    case 13:
      if (lookahead == 'A') ADVANCE(92);
      END_STATE();
    case 14:
      if (lookahead == 'A') ADVANCE(105);
      if (lookahead == 'E') ADVANCE(42);
      END_STATE();
    case 15:
      if (lookahead == 'A') ADVANCE(95);
      END_STATE();
    case 16:
      if (lookahead == 'A') ADVANCE(47);
      END_STATE();
    case 17:
      if (lookahead == 'A') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'B') ADVANCE(12);
      END_STATE();
    case 19:
      if (lookahead == 'C') ADVANCE(101);
      END_STATE();
    case 20:
      if (lookahead == 'C') ADVANCE(84);
      if (lookahead == 'S') ADVANCE(48);
      END_STATE();
    case 21:
      if (lookahead == 'C') ADVANCE(38);
      END_STATE();
    case 22:
      if (lookahead == 'C') ADVANCE(40);
      END_STATE();
    case 23:
      if (lookahead == 'D') ADVANCE(130);
      END_STATE();
    case 24:
      if (lookahead == 'D') ADVANCE(117);
      END_STATE();
    case 25:
      if (lookahead == 'D') ADVANCE(132);
      END_STATE();
    case 26:
      if (lookahead == 'D') ADVANCE(107);
      if (lookahead == 'P') ADVANCE(76);
      END_STATE();
    case 27:
      if (lookahead == 'D') ADVANCE(13);
      END_STATE();
    case 28:
      if (lookahead == 'D') ADVANCE(53);
      END_STATE();
    case 29:
      if (lookahead == 'E') ADVANCE(94);
      END_STATE();
    case 30:
      if (lookahead == 'E') ADVANCE(26);
      END_STATE();
    case 31:
      if (lookahead == 'E') ADVANCE(90);
      END_STATE();
    case 32:
      if (lookahead == 'E') ADVANCE(1);
      END_STATE();
    case 33:
      if (lookahead == 'E') ADVANCE(118);
      END_STATE();
    case 34:
      if (lookahead == 'E') ADVANCE(128);
      END_STATE();
    case 35:
      if (lookahead == 'E') ADVANCE(120);
      END_STATE();
    case 36:
      if (lookahead == 'E') ADVANCE(8);
      END_STATE();
    case 37:
      if (lookahead == 'E') ADVANCE(2);
      END_STATE();
    case 38:
      if (lookahead == 'E') ADVANCE(23);
      END_STATE();
    case 39:
      if (lookahead == 'E') ADVANCE(3);
      END_STATE();
    case 40:
      if (lookahead == 'E') ADVANCE(6);
      END_STATE();
    case 41:
      if (lookahead == 'F') ADVANCE(17);
      END_STATE();
    case 42:
      if (lookahead == 'F') ADVANCE(51);
      END_STATE();
    case 43:
      if (lookahead == 'G') ADVANCE(119);
      END_STATE();
    case 44:
      if (lookahead == 'G') ADVANCE(127);
      END_STATE();
    case 45:
      if (lookahead == 'G') ADVANCE(93);
      END_STATE();
    case 46:
      if (lookahead == 'G') ADVANCE(33);
      END_STATE();
    case 47:
      if (lookahead == 'G') ADVANCE(39);
      END_STATE();
    case 48:
      if (lookahead == 'I') ADVANCE(111);
      END_STATE();
    case 49:
      if (lookahead == 'I') ADVANCE(69);
      END_STATE();
    case 50:
      if (lookahead == 'I') ADVANCE(80);
      END_STATE();
    case 51:
      if (lookahead == 'I') ADVANCE(71);
      END_STATE();
    case 52:
      if (lookahead == 'I') ADVANCE(25);
      END_STATE();
    case 53:
      if (lookahead == 'I') ADVANCE(67);
      END_STATE();
    case 54:
      if (lookahead == 'I') ADVANCE(102);
      END_STATE();
    case 55:
      if (lookahead == 'I') ADVANCE(68);
      END_STATE();
    case 56:
      if (lookahead == 'L') ADVANCE(15);
      END_STATE();
    case 57:
      if (lookahead == 'L') ADVANCE(129);
      END_STATE();
    case 58:
      if (lookahead == 'L') ADVANCE(114);
      END_STATE();
    case 59:
      if (lookahead == 'L') ADVANCE(115);
      END_STATE();
    case 60:
      if (lookahead == 'L') ADVANCE(124);
      END_STATE();
    case 61:
      if (lookahead == 'L') ADVANCE(54);
      END_STATE();
    case 62:
      if (lookahead == 'M') ADVANCE(125);
      END_STATE();
    case 63:
      if (lookahead == 'N') ADVANCE(19);
      END_STATE();
    case 64:
      if (lookahead == 'N') ADVANCE(5);
      END_STATE();
    case 65:
      if (lookahead == 'N') ADVANCE(104);
      END_STATE();
    case 66:
      if (lookahead == 'N') ADVANCE(27);
      END_STATE();
    case 67:
      if (lookahead == 'N') ADVANCE(43);
      END_STATE();
    case 68:
      if (lookahead == 'N') ADVANCE(44);
      END_STATE();
    case 69:
      if (lookahead == 'N') ADVANCE(32);
      END_STATE();
    case 70:
      if (lookahead == 'N') ADVANCE(100);
      END_STATE();
    case 71:
      if (lookahead == 'N') ADVANCE(55);
      END_STATE();
    case 72:
      if (lookahead == 'O') ADVANCE(116);
      END_STATE();
    case 73:
      if (lookahead == 'O') ADVANCE(57);
      END_STATE();
    case 74:
      if (lookahead == 'O') ADVANCE(45);
      END_STATE();
    case 75:
      if (lookahead == 'O') ADVANCE(58);
      END_STATE();
    case 76:
      if (lookahead == 'O') ADVANCE(91);
      END_STATE();
    case 77:
      if (lookahead == 'O') ADVANCE(59);
      END_STATE();
    case 78:
      if (lookahead == 'O') ADVANCE(60);
      END_STATE();
    case 79:
      if (lookahead == 'O') ADVANCE(73);
      END_STATE();
    case 80:
      if (lookahead == 'O') ADVANCE(64);
      END_STATE();
    case 81:
      if (lookahead == 'O') ADVANCE(75);
      END_STATE();
    case 82:
      if (lookahead == 'O') ADVANCE(77);
      END_STATE();
    case 83:
      if (lookahead == 'O') ADVANCE(78);
      END_STATE();
    case 84:
      if (lookahead == 'O') ADVANCE(108);
      END_STATE();
    case 85:
      if (lookahead == 'P') ADVANCE(79);
      END_STATE();
    case 86:
      if (lookahead == 'P') ADVANCE(37);
      END_STATE();
    case 87:
      if (lookahead == 'P') ADVANCE(81);
      END_STATE();
    case 88:
      if (lookahead == 'P') ADVANCE(82);
      END_STATE();
    case 89:
      if (lookahead == 'P') ADVANCE(83);
      END_STATE();
    case 90:
      if (lookahead == 'R') ADVANCE(41);
      END_STATE();
    case 91:
      if (lookahead == 'R') ADVANCE(99);
      END_STATE();
    case 92:
      if (lookahead == 'R') ADVANCE(24);
      END_STATE();
    case 93:
      if (lookahead == 'R') ADVANCE(10);
      END_STATE();
    case 94:
      if (lookahead == 'S') ADVANCE(96);
      END_STATE();
    case 95:
      if (lookahead == 'S') ADVANCE(98);
      END_STATE();
    case 96:
      if (lookahead == 'S') ADVANCE(16);
      END_STATE();
    case 97:
      if (lookahead == 'S') ADVANCE(34);
      END_STATE();
    case 98:
      if (lookahead == 'S') ADVANCE(4);
      END_STATE();
    case 99:
      if (lookahead == 'T') ADVANCE(126);
      END_STATE();
    case 100:
      if (lookahead == 'T') ADVANCE(121);
      END_STATE();
    case 101:
      if (lookahead == 'T') ADVANCE(50);
      END_STATE();
    case 102:
      if (lookahead == 'T') ADVANCE(110);
      END_STATE();
    case 103:
      if (lookahead == 'T') ADVANCE(11);
      END_STATE();
    case 104:
      if (lookahead == 'T') ADVANCE(31);
      END_STATE();
    case 105:
      if (lookahead == 'T') ADVANCE(9);
      END_STATE();
    case 106:
      if (lookahead == 'U') ADVANCE(63);
      END_STATE();
    case 107:
      if (lookahead == 'U') ADVANCE(21);
      END_STATE();
    case 108:
      if (lookahead == 'U') ADVANCE(70);
      END_STATE();
    case 109:
      if (lookahead == 'Y') ADVANCE(86);
      END_STATE();
    case 110:
      if (lookahead == 'Y') ADVANCE(131);
      END_STATE();
    case 111:
      if (lookahead == 'Z') ADVANCE(35);
      END_STATE();
    case 112:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(112);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(133);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_CLASS_DASHPOOL);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_FUNCTION_DASHPOOL);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_NO);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_STANDARD);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_PAGE);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_HEADING);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_LINE_DASHSIZE);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_LINE_DASHCOUNT);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_interface_pool);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_PROGRAM);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_REPORT);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_DEFINING);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_DATABASE);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_TYPE_DASHPOOL);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_REDUCED);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_FUNCTIONALITY);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_MESSAGE_DASHID);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(133);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(134);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_terminate);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 112},
  [42] = {.lex_state = 112},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 112},
  [48] = {.lex_state = 112},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 112},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 112},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 112},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_CLASS_DASHPOOL] = ACTIONS(1),
    [anon_sym_FUNCTION_DASHPOOL] = ACTIONS(1),
    [anon_sym_NO] = ACTIONS(1),
    [anon_sym_STANDARD] = ACTIONS(1),
    [anon_sym_PAGE] = ACTIONS(1),
    [anon_sym_HEADING] = ACTIONS(1),
    [anon_sym_LINE_DASHSIZE] = ACTIONS(1),
    [anon_sym_LINE_DASHCOUNT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_interface_pool] = ACTIONS(1),
    [anon_sym_PROGRAM] = ACTIONS(1),
    [anon_sym_REPORT] = ACTIONS(1),
    [anon_sym_DEFINING] = ACTIONS(1),
    [anon_sym_DATABASE] = ACTIONS(1),
    [anon_sym_TYPE_DASHPOOL] = ACTIONS(1),
    [anon_sym_REDUCED] = ACTIONS(1),
    [anon_sym_FUNCTIONALITY] = ACTIONS(1),
    [anon_sym_MESSAGE_DASHID] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_terminate] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(50),
    [sym_introductory_statement] = STATE(39),
    [sym_class_pool] = STATE(36),
    [sym_function_pool] = STATE(36),
    [sym_program] = STATE(36),
    [sym_report] = STATE(36),
    [sym_type_pool] = STATE(36),
    [anon_sym_CLASS_DASHPOOL] = ACTIONS(3),
    [anon_sym_FUNCTION_DASHPOOL] = ACTIONS(5),
    [sym_interface_pool] = ACTIONS(7),
    [anon_sym_PROGRAM] = ACTIONS(9),
    [anon_sym_REPORT] = ACTIONS(11),
    [anon_sym_TYPE_DASHPOOL] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(15), 1,
      anon_sym_NO,
    ACTIONS(17), 1,
      anon_sym_LINE_DASHSIZE,
    ACTIONS(19), 1,
      anon_sym_LINE_DASHCOUNT,
    ACTIONS(21), 1,
      anon_sym_DEFINING,
    ACTIONS(23), 1,
      anon_sym_REDUCED,
    ACTIONS(25), 1,
      anon_sym_MESSAGE_DASHID,
    ACTIONS(27), 1,
      sym_terminate,
    STATE(14), 1,
      sym__message_id,
    STATE(20), 1,
      sym__reduced_functionality,
    STATE(3), 2,
      sym_list_options,
      aux_sym_function_pool_repeat1,
  [32] = 10,
    ACTIONS(15), 1,
      anon_sym_NO,
    ACTIONS(17), 1,
      anon_sym_LINE_DASHSIZE,
    ACTIONS(19), 1,
      anon_sym_LINE_DASHCOUNT,
    ACTIONS(23), 1,
      anon_sym_REDUCED,
    ACTIONS(25), 1,
      anon_sym_MESSAGE_DASHID,
    ACTIONS(29), 1,
      anon_sym_DEFINING,
    ACTIONS(31), 1,
      sym_terminate,
    STATE(13), 1,
      sym__message_id,
    STATE(19), 1,
      sym__reduced_functionality,
    STATE(6), 2,
      sym_list_options,
      aux_sym_function_pool_repeat1,
  [64] = 9,
    ACTIONS(15), 1,
      anon_sym_NO,
    ACTIONS(17), 1,
      anon_sym_LINE_DASHSIZE,
    ACTIONS(19), 1,
      anon_sym_LINE_DASHCOUNT,
    ACTIONS(23), 1,
      anon_sym_REDUCED,
    ACTIONS(25), 1,
      anon_sym_MESSAGE_DASHID,
    ACTIONS(33), 1,
      sym_terminate,
    STATE(17), 1,
      sym__message_id,
    STATE(27), 1,
      sym__reduced_functionality,
    STATE(5), 2,
      sym_list_options,
      aux_sym_function_pool_repeat1,
  [93] = 9,
    ACTIONS(15), 1,
      anon_sym_NO,
    ACTIONS(17), 1,
      anon_sym_LINE_DASHSIZE,
    ACTIONS(19), 1,
      anon_sym_LINE_DASHCOUNT,
    ACTIONS(23), 1,
      anon_sym_REDUCED,
    ACTIONS(25), 1,
      anon_sym_MESSAGE_DASHID,
    ACTIONS(35), 1,
      sym_terminate,
    STATE(18), 1,
      sym__message_id,
    STATE(37), 1,
      sym__reduced_functionality,
    STATE(6), 2,
      sym_list_options,
      aux_sym_function_pool_repeat1,
  [122] = 5,
    ACTIONS(37), 1,
      anon_sym_NO,
    ACTIONS(40), 1,
      anon_sym_LINE_DASHSIZE,
    ACTIONS(43), 1,
      anon_sym_LINE_DASHCOUNT,
    STATE(6), 2,
      sym_list_options,
      aux_sym_function_pool_repeat1,
    ACTIONS(46), 4,
      anon_sym_DEFINING,
      anon_sym_REDUCED,
      anon_sym_MESSAGE_DASHID,
      sym_terminate,
  [142] = 7,
    ACTIONS(15), 1,
      anon_sym_NO,
    ACTIONS(17), 1,
      anon_sym_LINE_DASHSIZE,
    ACTIONS(19), 1,
      anon_sym_LINE_DASHCOUNT,
    ACTIONS(25), 1,
      anon_sym_MESSAGE_DASHID,
    ACTIONS(48), 1,
      sym_terminate,
    STATE(33), 1,
      sym__message_id,
    STATE(8), 2,
      sym_list_options,
      aux_sym_function_pool_repeat1,
  [165] = 7,
    ACTIONS(15), 1,
      anon_sym_NO,
    ACTIONS(17), 1,
      anon_sym_LINE_DASHSIZE,
    ACTIONS(19), 1,
      anon_sym_LINE_DASHCOUNT,
    ACTIONS(25), 1,
      anon_sym_MESSAGE_DASHID,
    ACTIONS(50), 1,
      sym_terminate,
    STATE(24), 1,
      sym__message_id,
    STATE(6), 2,
      sym_list_options,
      aux_sym_function_pool_repeat1,
  [188] = 2,
    ACTIONS(54), 1,
      anon_sym_LPAREN,
    ACTIONS(52), 7,
      anon_sym_NO,
      anon_sym_LINE_DASHSIZE,
      anon_sym_LINE_DASHCOUNT,
      anon_sym_DEFINING,
      anon_sym_REDUCED,
      anon_sym_MESSAGE_DASHID,
      sym_terminate,
  [201] = 1,
    ACTIONS(52), 7,
      anon_sym_NO,
      anon_sym_LINE_DASHSIZE,
      anon_sym_LINE_DASHCOUNT,
      anon_sym_DEFINING,
      anon_sym_REDUCED,
      anon_sym_MESSAGE_DASHID,
      sym_terminate,
  [211] = 1,
    ACTIONS(56), 7,
      anon_sym_NO,
      anon_sym_LINE_DASHSIZE,
      anon_sym_LINE_DASHCOUNT,
      anon_sym_DEFINING,
      anon_sym_REDUCED,
      anon_sym_MESSAGE_DASHID,
      sym_terminate,
  [221] = 1,
    ACTIONS(58), 7,
      anon_sym_NO,
      anon_sym_LINE_DASHSIZE,
      anon_sym_LINE_DASHCOUNT,
      anon_sym_DEFINING,
      anon_sym_REDUCED,
      anon_sym_MESSAGE_DASHID,
      sym_terminate,
  [231] = 4,
    ACTIONS(23), 1,
      anon_sym_REDUCED,
    ACTIONS(60), 1,
      anon_sym_DEFINING,
    ACTIONS(62), 1,
      sym_terminate,
    STATE(22), 1,
      sym__reduced_functionality,
  [244] = 4,
    ACTIONS(23), 1,
      anon_sym_REDUCED,
    ACTIONS(29), 1,
      anon_sym_DEFINING,
    ACTIONS(31), 1,
      sym_terminate,
    STATE(19), 1,
      sym__reduced_functionality,
  [257] = 1,
    ACTIONS(64), 3,
      anon_sym_DEFINING,
      anon_sym_REDUCED,
      sym_terminate,
  [263] = 3,
    ACTIONS(25), 1,
      anon_sym_MESSAGE_DASHID,
    ACTIONS(66), 1,
      sym_terminate,
    STATE(28), 1,
      sym__message_id,
  [273] = 3,
    ACTIONS(23), 1,
      anon_sym_REDUCED,
    ACTIONS(35), 1,
      sym_terminate,
    STATE(37), 1,
      sym__reduced_functionality,
  [283] = 3,
    ACTIONS(23), 1,
      anon_sym_REDUCED,
    ACTIONS(68), 1,
      sym_terminate,
    STATE(45), 1,
      sym__reduced_functionality,
  [293] = 2,
    ACTIONS(60), 1,
      anon_sym_DEFINING,
    ACTIONS(62), 1,
      sym_terminate,
  [300] = 2,
    ACTIONS(29), 1,
      anon_sym_DEFINING,
    ACTIONS(31), 1,
      sym_terminate,
  [307] = 1,
    ACTIONS(70), 2,
      anon_sym_DEFINING,
      sym_terminate,
  [312] = 2,
    ACTIONS(72), 1,
      anon_sym_DEFINING,
    ACTIONS(74), 1,
      sym_terminate,
  [319] = 1,
    ACTIONS(76), 1,
      anon_sym_DATABASE,
  [323] = 1,
    ACTIONS(78), 1,
      sym_terminate,
  [327] = 1,
    ACTIONS(80), 1,
      sym_number,
  [331] = 1,
    ACTIONS(82), 1,
      anon_sym_FUNCTIONALITY,
  [335] = 1,
    ACTIONS(35), 1,
      sym_terminate,
  [339] = 1,
    ACTIONS(84), 1,
      sym_terminate,
  [343] = 1,
    ACTIONS(86), 1,
      anon_sym_STANDARD,
  [347] = 1,
    ACTIONS(88), 1,
      anon_sym_DATABASE,
  [351] = 1,
    ACTIONS(90), 1,
      sym_number,
  [355] = 1,
    ACTIONS(92), 1,
      sym_number,
  [359] = 1,
    ACTIONS(50), 1,
      sym_terminate,
  [363] = 1,
    ACTIONS(94), 1,
      anon_sym_HEADING,
  [367] = 1,
    ACTIONS(96), 1,
      sym_number,
  [371] = 1,
    ACTIONS(98), 1,
      sym_terminate,
  [375] = 1,
    ACTIONS(68), 1,
      sym_terminate,
  [379] = 1,
    ACTIONS(100), 1,
      ts_builtin_sym_end,
  [383] = 1,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
  [387] = 1,
    ACTIONS(104), 1,
      anon_sym_DATABASE,
  [391] = 1,
    ACTIONS(106), 1,
      sym_identifier,
  [395] = 1,
    ACTIONS(108), 1,
      sym_identifier,
  [399] = 1,
    ACTIONS(110), 1,
      sym_terminate,
  [403] = 1,
    ACTIONS(112), 1,
      anon_sym_RPAREN,
  [407] = 1,
    ACTIONS(114), 1,
      sym_terminate,
  [411] = 1,
    ACTIONS(74), 1,
      sym_terminate,
  [415] = 1,
    ACTIONS(116), 1,
      sym_identifier,
  [419] = 1,
    ACTIONS(118), 1,
      sym_identifier,
  [423] = 1,
    ACTIONS(120), 1,
      anon_sym_PAGE,
  [427] = 1,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
  [431] = 1,
    ACTIONS(124), 1,
      sym_terminate,
  [435] = 1,
    ACTIONS(126), 1,
      sym_identifier,
  [439] = 1,
    ACTIONS(128), 1,
      anon_sym_DATABASE,
  [443] = 1,
    ACTIONS(130), 1,
      sym_terminate,
  [447] = 1,
    ACTIONS(132), 1,
      sym_identifier,
  [451] = 1,
    ACTIONS(134), 1,
      sym_terminate,
  [455] = 1,
    ACTIONS(136), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 64,
  [SMALL_STATE(5)] = 93,
  [SMALL_STATE(6)] = 122,
  [SMALL_STATE(7)] = 142,
  [SMALL_STATE(8)] = 165,
  [SMALL_STATE(9)] = 188,
  [SMALL_STATE(10)] = 201,
  [SMALL_STATE(11)] = 211,
  [SMALL_STATE(12)] = 221,
  [SMALL_STATE(13)] = 231,
  [SMALL_STATE(14)] = 244,
  [SMALL_STATE(15)] = 257,
  [SMALL_STATE(16)] = 263,
  [SMALL_STATE(17)] = 273,
  [SMALL_STATE(18)] = 283,
  [SMALL_STATE(19)] = 293,
  [SMALL_STATE(20)] = 300,
  [SMALL_STATE(21)] = 307,
  [SMALL_STATE(22)] = 312,
  [SMALL_STATE(23)] = 319,
  [SMALL_STATE(24)] = 323,
  [SMALL_STATE(25)] = 327,
  [SMALL_STATE(26)] = 331,
  [SMALL_STATE(27)] = 335,
  [SMALL_STATE(28)] = 339,
  [SMALL_STATE(29)] = 343,
  [SMALL_STATE(30)] = 347,
  [SMALL_STATE(31)] = 351,
  [SMALL_STATE(32)] = 355,
  [SMALL_STATE(33)] = 359,
  [SMALL_STATE(34)] = 363,
  [SMALL_STATE(35)] = 367,
  [SMALL_STATE(36)] = 371,
  [SMALL_STATE(37)] = 375,
  [SMALL_STATE(38)] = 379,
  [SMALL_STATE(39)] = 383,
  [SMALL_STATE(40)] = 387,
  [SMALL_STATE(41)] = 391,
  [SMALL_STATE(42)] = 395,
  [SMALL_STATE(43)] = 399,
  [SMALL_STATE(44)] = 403,
  [SMALL_STATE(45)] = 407,
  [SMALL_STATE(46)] = 411,
  [SMALL_STATE(47)] = 415,
  [SMALL_STATE(48)] = 419,
  [SMALL_STATE(49)] = 423,
  [SMALL_STATE(50)] = 427,
  [SMALL_STATE(51)] = 431,
  [SMALL_STATE(52)] = 435,
  [SMALL_STATE(53)] = 439,
  [SMALL_STATE(54)] = 443,
  [SMALL_STATE(55)] = 447,
  [SMALL_STATE(56)] = 451,
  [SMALL_STATE(57)] = 455,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_report, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_report, 3, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 3, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_pool_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_pool_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_pool_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_pool_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_pool, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_pool, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_options, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_options, 4, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_options, 5, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_report, 4, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__message_id, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_pool, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 4, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__reduced_functionality, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_report, 5, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_pool, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_pool, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_introductory_statement, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_pool, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 5, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [122] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_report, 6, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_report, 7, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_report, 8, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_abap_parser(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "abap_parser",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
